
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felip
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Civil = new javax.swing.ButtonGroup();
        P_BG = new javax.swing.JPanel();
        Tabs = new javax.swing.JTabbedPane();
        T_Cperson = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        cb_TipoC = new javax.swing.JComboBox<>();
        Txt_tp = new javax.swing.JLabel();
        tf_ID = new javax.swing.JFormattedTextField();
        Txt_id = new javax.swing.JLabel();
        tf_AGE = new javax.swing.JFormattedTextField();
        Txt_edad = new javax.swing.JLabel();
        Txt_nomb = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        Btn_M = new javax.swing.JRadioButton();
        Btn_F = new javax.swing.JRadioButton();
        Txt_sex = new javax.swing.JLabel();
        Btn_C = new javax.swing.JRadioButton();
        Btn_S = new javax.swing.JRadioButton();
        Txt_civil = new javax.swing.JLabel();
        tf_alt = new javax.swing.JFormattedTextField();
        Txt_alt = new javax.swing.JLabel();
        tf_peso = new javax.swing.JFormattedTextField();
        Txt_peso = new javax.swing.JLabel();
        lbs0 = new javax.swing.JLabel();
        cms = new javax.swing.JLabel();
        Txt_G = new javax.swing.JLabel();
        Txt_PG = new javax.swing.JLabel();
        Btn_AgregarP = new javax.swing.JButton();
        Txt_Pass = new javax.swing.JLabel();
        Txt_Usern = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        Txt_Cargo = new javax.swing.JLabel();
        cb_carg = new javax.swing.JComboBox<>();
        Txt_Ocup = new javax.swing.JLabel();
        tf_ocup = new javax.swing.JTextField();
        Txt_Hor = new javax.swing.JLabel();
        tf_hor = new javax.swing.JTextField();
        Txt_tiemp = new javax.swing.JLabel();
        tf_tiemp = new javax.swing.JFormattedTextField();
        Txt_sueld = new javax.swing.JLabel();
        tf_sueld = new javax.swing.JFormattedTextField();
        lps = new javax.swing.JLabel();
        semanas = new javax.swing.JLabel();
        unico = new javax.swing.JLabel();
        unico2 = new javax.swing.JLabel();
        T_Cobj = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        Txt_to = new javax.swing.JLabel();
        cb_TipoO = new javax.swing.JComboBox<>();
        Txt_Color = new javax.swing.JLabel();
        Txt_Desc = new javax.swing.JLabel();
        sp_Desc = new javax.swing.JScrollPane();
        ta_desc = new javax.swing.JTextArea();
        Txt_Marca = new javax.swing.JLabel();
        tf_Marca = new javax.swing.JTextField();
        Txt_Tamaño = new javax.swing.JLabel();
        tf_Tamaño = new javax.swing.JFormattedTextField();
        Txt_Calidad = new javax.swing.JLabel();
        tf_Calidad = new javax.swing.JTextField();
        Txt_personadd = new javax.swing.JLabel();
        cb_personas = new javax.swing.JComboBox<>();
        btn_color = new javax.swing.JButton();
        Btn_addO = new javax.swing.JButton();
        Txt_Z = new javax.swing.JLabel();
        Txt_R = new javax.swing.JLabel();
        Txt_H = new javax.swing.JLabel();
        Txt_ta = new javax.swing.JLabel();
        tf_com = new javax.swing.JFormattedTextField();
        Txt_Desc1 = new javax.swing.JLabel();
        sp_Desc1 = new javax.swing.JScrollPane();
        ta_descS = new javax.swing.JTextArea();
        Txt_tall = new javax.swing.JLabel();
        tf_ta1 = new javax.swing.JFormattedTextField();
        Txt_com1 = new javax.swing.JLabel();
        cb_tall = new javax.swing.JComboBox<>();
        Txt_tel = new javax.swing.JLabel();
        tf_tel = new javax.swing.JTextField();
        Txt_pais = new javax.swing.JLabel();
        tf_pais = new javax.swing.JTextField();
        Txt_desc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descH = new javax.swing.JTextArea();
        Txt_inst = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_inst = new javax.swing.JTextArea();
        Txt_Gar = new javax.swing.JLabel();
        tf_gar = new javax.swing.JFormattedTextField();
        meses = new javax.swing.JLabel();
        T_Mperson = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        T_Mobj = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        T_Jperson = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        T_Jobj = new javax.swing.JPanel();
        title5 = new javax.swing.JLabel();
        T_Lperson = new javax.swing.JPanel();
        title6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListP = new javax.swing.JTable();
        Eliminst = new javax.swing.JLabel();
        Btn_ElimP = new javax.swing.JButton();
        T_Lobj = new javax.swing.JPanel();
        title7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListO = new javax.swing.JTable();
        Eliminst2 = new javax.swing.JLabel();
        Btn_ElimO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda");
        setResizable(false);

        P_BG.setBackground(new java.awt.Color(102, 102, 102));

        Tabs.setBackground(new java.awt.Color(51, 51, 51));
        Tabs.setForeground(new java.awt.Color(0, 0, 0));
        Tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabsMouseClicked(evt);
            }
        });

        T_Cperson.setBackground(new java.awt.Color(102, 102, 102));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setText("CREAR PERSONA");

        cb_TipoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opcion", "Persona General", "Gerente" }));
        cb_TipoC.setToolTipText("");
        cb_TipoC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoCItemStateChanged(evt);
            }
        });

        Txt_tp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_tp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_tp.setText("Tipo de Persona:");

        tf_ID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        Txt_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_id.setText("ID:");

        tf_AGE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AGEActionPerformed(evt);
            }
        });

        Txt_edad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_edad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_edad.setText("Edad:");

        Txt_nomb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_nomb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_nomb.setText("Nombre:");

        Genero.add(Btn_M);
        Btn_M.setText("Masculino");

        Genero.add(Btn_F);
        Btn_F.setText("Femenino");

        Txt_sex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_sex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_sex.setText("Sexo:");

        Civil.add(Btn_C);
        Btn_C.setText("Casado");

        Civil.add(Btn_S);
        Btn_S.setText("Soltero");

        Txt_civil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_civil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_civil.setText("Estado Civil:");

        tf_alt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        Txt_alt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_alt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_alt.setText("Altura:");

        tf_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        Txt_peso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_peso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_peso.setText("Peso:");

        lbs0.setText("lbs");

        cms.setText("cms");

        Txt_G.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_G.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_G.setText("GERENTE");

        Txt_PG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_PG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_PG.setText("PERSONA GENERAL");

        Btn_AgregarP.setText("Agregar Persona");
        Btn_AgregarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_AgregarP.setEnabled(false);
        Btn_AgregarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_AgregarPMouseClicked(evt);
            }
        });

        Txt_Pass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Pass.setText("Contraseña:");

        Txt_Usern.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Usern.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Usern.setText("Nombre de Usuario:");

        tf_Username.setEnabled(false);

        pf_pass.setEnabled(false);

        Txt_Cargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Cargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Cargo.setText("Cargo:");

        cb_carg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente de planta", "Gerente de sucursal" }));
        cb_carg.setEnabled(false);

        Txt_Ocup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Ocup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Ocup.setText("Ocupacion:");

        tf_ocup.setEnabled(false);

        Txt_Hor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Hor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Hor.setText("Horario:");

        tf_hor.setEnabled(false);

        Txt_tiemp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_tiemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_tiemp.setText("Tiempo Trabajando:");

        tf_tiemp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_tiemp.setEnabled(false);
        tf_tiemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tiempActionPerformed(evt);
            }
        });

        Txt_sueld.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_sueld.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_sueld.setText("Sueldo:");

        tf_sueld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_sueld.setEnabled(false);

        lps.setText("lps");

        semanas.setText("Semanas");

        unico.setText("unico");

        unico2.setText("unico");

        javax.swing.GroupLayout T_CpersonLayout = new javax.swing.GroupLayout(T_Cperson);
        T_Cperson.setLayout(T_CpersonLayout);
        T_CpersonLayout.setHorizontalGroup(
            T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CpersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(328, 328, 328))
            .addGroup(T_CpersonLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ID)
                            .addComponent(cb_TipoC, 0, 188, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cms, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(Txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbs0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txt_G, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(T_CpersonLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(Btn_M, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_F, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addComponent(Txt_nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(Txt_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addComponent(Btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_S, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txt_PG))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(T_CpersonLayout.createSequentialGroup()
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, T_CpersonLayout.createSequentialGroup()
                                        .addGap(182, 182, 182)
                                        .addComponent(tf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(T_CpersonLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                                .addComponent(Txt_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cb_carg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                                .addComponent(Txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(25, 25, 25)
                                .addComponent(unico2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(Btn_AgregarP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addComponent(Txt_sueld, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_sueld))
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addComponent(Txt_Ocup, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ocup, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addComponent(Txt_Hor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_hor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(T_CpersonLayout.createSequentialGroup()
                                .addComponent(Txt_tiemp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tiemp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lps, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semanas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(unico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(T_CpersonLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(Txt_Usern, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(812, Short.MAX_VALUE)))
        );
        T_CpersonLayout.setVerticalGroup(
            T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_CpersonLayout.createSequentialGroup()
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_TipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cms)
                            .addComponent(lbs0))
                        .addGap(42, 42, 42)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unico)
                        .addGap(26, 26, 26)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_M)
                            .addComponent(Btn_F)
                            .addComponent(Txt_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_C)
                            .addComponent(Btn_S)
                            .addComponent(Txt_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_PG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unico2)))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Ocup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ocup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Hor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_tiemp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tiemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semanas))))
                .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Btn_AgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_carg)
                            .addComponent(Txt_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                    .addGroup(T_CpersonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_sueld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_sueld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lps))))
                .addGap(14, 14, 14))
            .addGroup(T_CpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CpersonLayout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(Txt_Usern, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(153, 153, 153)))
        );

        Tabs.addTab("Crear Persona", T_Cperson);

        T_Cobj.setBackground(new java.awt.Color(102, 102, 102));

        title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 0, 0));
        title1.setText("CREAR OBJETO");

        Txt_to.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_to.setText("Tipo de Objeto:");

        cb_TipoO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opcion", "Zapatos", "Ropa", "De Hogar" }));
        cb_TipoO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoOItemStateChanged(evt);
            }
        });

        Txt_Color.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Color.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Color.setText("Color:");

        Txt_Desc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Desc.setText("Descripcion:");

        ta_desc.setColumns(20);
        ta_desc.setRows(5);
        sp_Desc.setViewportView(ta_desc);

        Txt_Marca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Marca.setText("Marca:");

        tf_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MarcaActionPerformed(evt);
            }
        });

        Txt_Tamaño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Tamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Tamaño.setText("Tamaño:");

        tf_Tamaño.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        Txt_Calidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Calidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Calidad.setText("Calidad:");

        tf_Calidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CalidadActionPerformed(evt);
            }
        });

        Txt_personadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_personadd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_personadd.setText("Persona que lo agrego:");

        btn_color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_colorMouseClicked(evt);
            }
        });
        btn_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorActionPerformed(evt);
            }
        });

        Btn_addO.setText("Agregar Objeto");
        Btn_addO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_addO.setEnabled(false);
        Btn_addO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_addOMouseClicked(evt);
            }
        });
        Btn_addO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addOActionPerformed(evt);
            }
        });

        Txt_Z.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_Z.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Z.setText("ZAPATOS");

        Txt_R.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_R.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_R.setText("ROPA");

        Txt_H.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_H.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_H.setText("HOGAR");

        Txt_ta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_ta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_ta.setText("Talla:");

        tf_com.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_com.setEnabled(false);

        Txt_Desc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Desc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Desc1.setText("Descripcion de la suela:");

        ta_descS.setColumns(20);
        ta_descS.setRows(5);
        ta_descS.setEnabled(false);
        sp_Desc1.setViewportView(ta_descS);

        Txt_tall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_tall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_tall.setText("Talla:");

        tf_ta1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_ta1.setEnabled(false);

        Txt_com1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_com1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_com1.setText("Comodidad (1-10):");

        cb_tall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL" }));
        cb_tall.setEnabled(false);
        cb_tall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tallActionPerformed(evt);
            }
        });

        Txt_tel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_tel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_tel.setText("Tipo de tela:");

        tf_tel.setEnabled(false);

        Txt_pais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_pais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_pais.setText("Pais elab:");

        tf_pais.setEnabled(false);

        Txt_desc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_desc.setText("Descripcion:");

        ta_descH.setColumns(20);
        ta_descH.setRows(5);
        ta_descH.setEnabled(false);
        jScrollPane3.setViewportView(ta_descH);

        Txt_inst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_inst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_inst.setText("Instrucciones:");

        ta_inst.setColumns(20);
        ta_inst.setRows(5);
        ta_inst.setEnabled(false);
        jScrollPane4.setViewportView(ta_inst);

        Txt_Gar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Txt_Gar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Gar.setText("Garantia:");

        tf_gar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_gar.setEnabled(false);

        meses.setText("Meses");

        javax.swing.GroupLayout T_CobjLayout = new javax.swing.GroupLayout(T_Cobj);
        T_Cobj.setLayout(T_CobjLayout);
        T_CobjLayout.setHorizontalGroup(
            T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CobjLayout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(title1)
                .addGap(328, 328, 328))
            .addGroup(T_CobjLayout.createSequentialGroup()
                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_Calidad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(T_CobjLayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Txt_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Txt_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Txt_to, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CobjLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Txt_personadd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T_CobjLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_TipoO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_Desc)
                                    .addComponent(tf_Marca)
                                    .addComponent(tf_Tamaño)
                                    .addComponent(tf_Calidad)
                                    .addComponent(cb_personas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(T_CobjLayout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Txt_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(T_CobjLayout.createSequentialGroup()
                                                    .addComponent(Txt_tall, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cb_tall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(36, 36, 36)
                                                    .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(T_CobjLayout.createSequentialGroup()
                                                            .addComponent(Txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(T_CobjLayout.createSequentialGroup()
                                                            .addComponent(Txt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, T_CobjLayout.createSequentialGroup()
                                                    .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, T_CobjLayout.createSequentialGroup()
                                                            .addGap(127, 127, 127)
                                                            .addComponent(tf_com, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Txt_H, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Txt_R, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(225, 225, 225)))))
                                    .addGroup(T_CobjLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(Txt_Desc1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sp_Desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CobjLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(T_CobjLayout.createSequentialGroup()
                                                .addComponent(Txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(T_CobjLayout.createSequentialGroup()
                                                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Txt_Gar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Txt_inst, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(T_CobjLayout.createSequentialGroup()
                                                        .addComponent(tf_gar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(meses, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(79, 79, 79))))
                            .addGroup(T_CobjLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)
                                .addComponent(Txt_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ta1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Btn_addO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CobjLayout.createSequentialGroup()
                    .addContainerGap(484, Short.MAX_VALUE)
                    .addComponent(Txt_com1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(378, 378, 378)))
        );
        T_CobjLayout.setVerticalGroup(
            T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_CobjLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_to, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_TipoO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Txt_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Txt_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ta1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(T_CobjLayout.createSequentialGroup()
                                .addComponent(sp_Desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tf_com, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_tall, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_tall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_tel)
                        .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_pais)
                    .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Calidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Calidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_personadd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_addO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Gar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(T_CobjLayout.createSequentialGroup()
                        .addComponent(Txt_H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_inst, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_gar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meses))
                        .addGap(0, 24, Short.MAX_VALUE))))
            .addGroup(T_CobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(T_CobjLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(Txt_com1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        Tabs.addTab("Crear Objeto", T_Cobj);

        T_Mperson.setBackground(new java.awt.Color(102, 102, 102));

        title2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 0, 0));
        title2.setText("MODIFICAR PERSONA");

        javax.swing.GroupLayout T_MpersonLayout = new javax.swing.GroupLayout(T_Mperson);
        T_Mperson.setLayout(T_MpersonLayout);
        T_MpersonLayout.setHorizontalGroup(
            T_MpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_MpersonLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(title2)
                .addGap(328, 328, 328))
        );
        T_MpersonLayout.setVerticalGroup(
            T_MpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_MpersonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        Tabs.addTab("Modificar Persona", T_Mperson);

        T_Mobj.setBackground(new java.awt.Color(102, 102, 102));

        title3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 0, 0));
        title3.setText("MODIFICAR OBJETO");

        javax.swing.GroupLayout T_MobjLayout = new javax.swing.GroupLayout(T_Mobj);
        T_Mobj.setLayout(T_MobjLayout);
        T_MobjLayout.setHorizontalGroup(
            T_MobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_MobjLayout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(title3)
                .addGap(328, 328, 328))
        );
        T_MobjLayout.setVerticalGroup(
            T_MobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_MobjLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        Tabs.addTab("Modificar Objeto", T_Mobj);

        T_Jperson.setBackground(new java.awt.Color(102, 102, 102));

        title4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 0, 0));
        title4.setText("JERARQUIA DE PERSONAS");

        javax.swing.GroupLayout T_JpersonLayout = new javax.swing.GroupLayout(T_Jperson);
        T_Jperson.setLayout(T_JpersonLayout);
        T_JpersonLayout.setHorizontalGroup(
            T_JpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_JpersonLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(title4)
                .addGap(328, 328, 328))
        );
        T_JpersonLayout.setVerticalGroup(
            T_JpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_JpersonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        Tabs.addTab("Jerarquia de Personas", T_Jperson);

        T_Jobj.setBackground(new java.awt.Color(102, 102, 102));

        title5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title5.setForeground(new java.awt.Color(255, 0, 0));
        title5.setText("JERARQUIA DE OBJETOS");

        javax.swing.GroupLayout T_JobjLayout = new javax.swing.GroupLayout(T_Jobj);
        T_Jobj.setLayout(T_JobjLayout);
        T_JobjLayout.setHorizontalGroup(
            T_JobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_JobjLayout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(title5)
                .addGap(328, 328, 328))
        );
        T_JobjLayout.setVerticalGroup(
            T_JobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_JobjLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        Tabs.addTab("Jerarquia de Objetos", T_Jobj);

        T_Lperson.setBackground(new java.awt.Color(102, 102, 102));

        title6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title6.setForeground(new java.awt.Color(255, 0, 0));
        title6.setText("LISTAR PERSONAS");

        ListP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ));
        jScrollPane1.setViewportView(ListP);

        Eliminst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Eliminst.setText("SELECCIONE A UNA PERSONA Y LUEGO DELE CLICK A \"ELIMINAR\" PARA ELIMINARLAS DE LA LISTA");

        Btn_ElimP.setForeground(new java.awt.Color(255, 0, 0));
        Btn_ElimP.setText("ELIMINAR");
        Btn_ElimP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_ElimP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ElimPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_LpersonLayout = new javax.swing.GroupLayout(T_Lperson);
        T_Lperson.setLayout(T_LpersonLayout);
        T_LpersonLayout.setHorizontalGroup(
            T_LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LpersonLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(T_LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LpersonLayout.createSequentialGroup()
                        .addComponent(title6)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LpersonLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LpersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Eliminst)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(T_LpersonLayout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(Btn_ElimP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        T_LpersonLayout.setVerticalGroup(
            T_LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_LpersonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_ElimP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Tabs.addTab("Listar Personas", T_Lperson);

        T_Lobj.setBackground(new java.awt.Color(102, 102, 102));

        title7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title7.setForeground(new java.awt.Color(255, 0, 0));
        title7.setText("LISTAR OBJETOS");

        ListO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Persona que lo ingreso"
            }
        ));
        jScrollPane2.setViewportView(ListO);

        Eliminst2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Eliminst2.setText("SELECCIONE UN OBJETO Y LUEGO DELE CLICK A \"ELIMINAR\" PARA ELIMINARLAS DE LA LISTA");

        Btn_ElimO.setForeground(new java.awt.Color(255, 0, 0));
        Btn_ElimO.setText("ELIMINAR");
        Btn_ElimO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_ElimO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ElimOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_LobjLayout = new javax.swing.GroupLayout(T_Lobj);
        T_Lobj.setLayout(T_LobjLayout);
        T_LobjLayout.setHorizontalGroup(
            T_LobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_LobjLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(T_LobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LobjLayout.createSequentialGroup()
                        .addComponent(title7)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LobjLayout.createSequentialGroup()
                        .addGroup(T_LobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_LobjLayout.createSequentialGroup()
                                .addComponent(Eliminst2)
                                .addGap(69, 69, 69))
                            .addGroup(T_LobjLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(Btn_ElimO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(274, 274, 274)))
                        .addGap(107, 107, 107))))
        );
        T_LobjLayout.setVerticalGroup(
            T_LobjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_LobjLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminst2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_ElimO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Tabs.addTab("Listar Objetos", T_Lobj);

        javax.swing.GroupLayout P_BGLayout = new javax.swing.GroupLayout(P_BG);
        P_BG.setLayout(P_BGLayout);
        P_BGLayout.setHorizontalGroup(
            P_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );
        P_BGLayout.setVerticalGroup(
            P_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_TipoCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoCItemStateChanged
        // TODO add your handling code here:
        
        if(cb_TipoC.getSelectedIndex() == 0){
            Btn_AgregarP.setEnabled(false);
            
            tf_Username.setEnabled(false);
            pf_pass.setEnabled(false);
            cb_carg.setEnabled(false);
            
            tf_ocup.setEnabled(false);
            tf_hor.setEnabled(false);
            tf_tiemp.setEnabled(false);
            tf_sueld.setEnabled(false);
        }else if(cb_TipoC.getSelectedIndex() == 1){
            Btn_AgregarP.setEnabled(true);
            tf_Username.setEnabled(false);
            pf_pass.setEnabled(false);
            cb_carg.setEnabled(false);
            
            tf_ocup.setEnabled(true);
            tf_hor.setEnabled(true);
            tf_tiemp.setEnabled(true);
            tf_sueld.setEnabled(true);
            
        }else if(cb_TipoC.getSelectedIndex() == 2){
            Btn_AgregarP.setEnabled(true);
            tf_ocup.setEnabled(false);
            tf_hor.setEnabled(false);
            tf_tiemp.setEnabled(false);
            tf_sueld.setEnabled(false);
            
            tf_Username.setEnabled(true);
            pf_pass.setEnabled(true);
            cb_carg.setEnabled(true);
        }
        
    }//GEN-LAST:event_cb_TipoCItemStateChanged

    private void tf_AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AGEActionPerformed

    private void Btn_AgregarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AgregarPMouseClicked
        // TODO add your handling code here:
        String ID = tf_ID.getText();
        int cont = 0;
        for (int i = 0; i < IDs.size(); i++) {
            if(IDs.get(i).equals(ID)){
                cont++;
            }
        }
        String Nombre = tf_Nombre.getText();
        String age = tf_AGE.getText();
        
        String sexo;
        if(Btn_M.isSelected()){
            sexo = "Masculino";
        }else if(Btn_F.isSelected()){
            sexo = "Femenino";
        }else{
            sexo = "null";
        }
        
        String Civil;
        if(Btn_C.isSelected()){
            Civil = "Casado";
        }else if(Btn_S.isSelected()){
            Civil = "Soltero";
        }else{
            Civil = "Null";
        }
        
        String height = tf_alt.getText();
        String weight = tf_peso.getText();
        
        
        
        if(tf_ID.getText().isBlank() || tf_Nombre.getText().isBlank() || tf_AGE.getText().isBlank() || sexo.equals("Null") || Civil.equals("Null") || tf_alt.getText().isBlank() || tf_peso.getText().isBlank() || cont > 0){
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }else{
            int edad = Integer.parseInt(age);
            int altura = Integer.parseInt(height);
            int peso = Integer.parseInt(weight);
            
            if(cb_TipoC.getSelectedIndex() == 1){
            
                String Ocupacion = tf_ocup.getText();
                String Horario = tf_hor.getText();
                String Weeks = tf_tiemp.getText();
                String Sal = tf_sueld.getText();
                
                if(tf_ocup.getText().isBlank() || tf_hor.getText().isBlank() || tf_tiemp.getText().isBlank() || tf_sueld.getText().isBlank()){
                     JOptionPane.showMessageDialog(this, "No se pudo agregar");
                }else{
                    int Semanas = Integer.parseInt(Weeks);
                    int Sueldo = Integer.parseInt(Sal);
                    
                    PGeneral Person = new PGeneral(Ocupacion, Horario, Semanas, Sueldo, ID, Nombre, edad, sexo, Civil, altura, peso);
                    P.add(Person);
                    
                    IDs.add(ID);
                    JOptionPane.showMessageDialog(this, "Persona agregada exitosamente");
                }
                
                
                
            }else if(cb_TipoC.getSelectedIndex() == 2){
                String Usuario = tf_Username.getText();
                int cont2 = 0;
                 for (int i = 0; i < Users.size(); i++) {
                    if(Users.get(i).equals(Usuario)){
                        cont2++;
                    }
                }
                String Contraseña = pf_pass.getText();
                
                String Cargo;
                if(cb_carg.getSelectedIndex() == 0){
                    Cargo = "Gerente de Planta";
                }else if(cb_carg.getSelectedIndex() == 1){ 
                    Cargo = "Gerente de sucursal";
                }else{
                    Cargo = "Null";
                }           
                
                if(tf_Username.getText().isBlank() || pf_pass.getText().isBlank() || Cargo.equals("Null") || cont2 > 0){
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                }else{
                    Gerente Person = new Gerente(Usuario, Contraseña, Cargo, ID, Nombre, edad, sexo, Civil, altura, peso);
                    P.add(Person);
                    
                    
                    IDs.add(ID);
                    JOptionPane.showMessageDialog(this, "Persona agregada exitosamente");
                }
            }
        }
    }//GEN-LAST:event_Btn_AgregarPMouseClicked

    private void Btn_ElimPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ElimPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ElimPActionPerformed

    private void Btn_ElimOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ElimOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ElimOActionPerformed

    private void tf_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MarcaActionPerformed

    private void tf_CalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_CalidadActionPerformed

    private void TabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabsMouseClicked
        // TODO add your handling code here:
        cb_personas.removeAllItems();
        PersonComboLlenar();
    }//GEN-LAST:event_TabsMouseClicked

    private void tf_tiempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tiempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tiempActionPerformed

    private void btn_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorActionPerformed

    private void btn_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_colorMouseClicked
        // TODO add your handling code here:
        btn_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_btn_colorMouseClicked

    private void Btn_addOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addOActionPerformed
        // TODO add your handling code here:
        Color color = btn_color.getBackground();
        String Descripcion = ta_desc.getText();
        String Marca = tf_Marca.getText();
        String Size = tf_Tamaño.getText();
        String Calidad = tf_Calidad.getText();
        
        int pi = cb_personas.getSelectedIndex();
        
        Persona Ingreso;
        int Tamaño;
        
        if(ta_desc.getText().isBlank() || tf_Marca.getText().isBlank() || tf_Tamaño.getText().isBlank() || tf_Calidad.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }else{
            Tamaño = Integer.parseInt(Size);
            
            if(cb_TipoO.getSelectedIndex() == 1){
                
                String tal = tf_ta1.getText();
                String DescripcionSuel = ta_descS.getText();
                String como = tf_com.getText();
                
                if(tf_ta1.getText().isBlank() || ta_descS.getText().isBlank() || tf_com.getText().isBlank()){
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                }else{
                    
                    int talla = Integer.parseInt(tal);
                    int comodidad = Integer.parseInt(como);
                    
                    Ingreso = P.get(pi);
                    Zapatos zap = new Zapatos(talla, DescripcionSuel, comodidad, color, Descripcion, Marca, Tamaño, Calidad, Ingreso);
                    O.add(zap);
                    
                    JOptionPane.showMessageDialog(this, "Objeto agregado");
                }
                
            }else if(cb_TipoO.getSelectedIndex() == 2){
                
                String tal = (String)cb_tall.getSelectedItem();
                String tela = tf_tel.getText();
                String pais = tf_pais.getText();
                
                if(tf_tel.getText().isBlank() || tf_pais.getText().isBlank()){
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                }else{
                    int talla = Integer.parseInt(tal);
                    
                    Ingreso = P.get(pi);
                    Ropa rop = new Ropa(talla, tela, pais, color, Descripcion, Marca, Tamaño, Calidad, Ingreso);
                    O.add(rop);
                    JOptionPane.showMessageDialog(this, "Objeto agregado");
                }
                
            }else if(cb_TipoO.getSelectedIndex() == 3){
                
                String LugarC = ta_descH.getText();
                String Inst = ta_inst.getText();
                String gar = tf_gar.getText();
                
                if(ta_descH.getText().isBlank() || ta_inst.getText().isBlank() || tf_gar.getText().isBlank()){
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                }else{
                    
                    int garantia = Integer.parseInt(gar);
                    
                    Ingreso = P.get(pi);
                    Hogar hog = new Hogar(LugarC, Inst, garantia, color, Descripcion, Marca, Tamaño, Calidad, Ingreso);
                    O.add(hog);
                    JOptionPane.showMessageDialog(this, "Objeto agregado");
                }
                
    
            }
        }
    }//GEN-LAST:event_Btn_addOActionPerformed

    private void Btn_addOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_addOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_addOMouseClicked

    private void cb_TipoOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoOItemStateChanged
        // TODO add your handling code here:
        if(cb_TipoO.getSelectedIndex() == 0){
            Btn_addO.setEnabled(false);
            
            cb_tall.setEnabled(false);
            tf_tel.setEnabled(false);
            tf_pais.setEnabled(false);
            tf_ta1.setEnabled(false);
            ta_descS.setEnabled(false);
            tf_com.setEnabled(false);
            ta_descH.setEnabled(false);
            ta_inst.setEnabled(false);
            tf_gar.setEnabled(false);
            
        }else if(cb_TipoO.getSelectedIndex() == 1){
            Btn_addO.setEnabled(true);
             
            tf_ta1.setEnabled(true);
            ta_descS.setEnabled(true);
            tf_com.setEnabled(true);
            
            cb_tall.setEnabled(false);
            tf_tel.setEnabled(false);
            tf_pais.setEnabled(false);
            ta_descH.setEnabled(false);
            ta_inst.setEnabled(false);
            tf_gar.setEnabled(false);
            
        }else if(cb_TipoO.getSelectedIndex() == 2){
            Btn_addO.setEnabled(true);
            
            cb_tall.setEnabled(true);
            tf_tel.setEnabled(true);
            tf_pais.setEnabled(true);
            
            tf_ta1.setEnabled(false);
            ta_descS.setEnabled(false);
            tf_com.setEnabled(false);
            ta_descH.setEnabled(false);
            ta_inst.setEnabled(false);
            tf_gar.setEnabled(false);
            
        }else if(cb_TipoO.getSelectedIndex() == 3){
            Btn_addO.setEnabled(true);
            
            ta_descH.setEnabled(true);
            ta_inst.setEnabled(true);
            tf_gar.setEnabled(true);
            
            cb_tall.setEnabled(false);
            tf_tel.setEnabled(false);
            tf_pais.setEnabled(false);
            tf_ta1.setEnabled(false);
            ta_descS.setEnabled(false);
            tf_com.setEnabled(false);
        }
    }//GEN-LAST:event_cb_TipoOItemStateChanged

    private void cb_tallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void PersonComboLlenar(){
        for (Persona P : P) {
            cb_personas.addItem(P.getNombre());
        }
    }
    
    
    
    ArrayList<String> IDs = new ArrayList();
    ArrayList<String> Users = new ArrayList();
    ArrayList<Persona> P = new ArrayList();
    ArrayList<Objetos> O = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AgregarP;
    private javax.swing.JRadioButton Btn_C;
    private javax.swing.JButton Btn_ElimO;
    private javax.swing.JButton Btn_ElimP;
    private javax.swing.JRadioButton Btn_F;
    private javax.swing.JRadioButton Btn_M;
    private javax.swing.JRadioButton Btn_S;
    private javax.swing.JButton Btn_addO;
    private javax.swing.JPanel C_Tab2;
    private javax.swing.JPanel C_Tab3;
    private javax.swing.JPanel C_Tab4;
    private javax.swing.JPanel C_Tab5;
    private javax.swing.ButtonGroup Civil;
    private javax.swing.JLabel Eliminst;
    private javax.swing.JLabel Eliminst2;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JTable ListO;
    private javax.swing.JTable ListP;
    private javax.swing.JPanel P_BG;
    private javax.swing.JPanel T_Cobj;
    private javax.swing.JPanel T_Cperson;
    private javax.swing.JPanel T_Jobj;
    private javax.swing.JPanel T_Jperson;
    private javax.swing.JPanel T_Lobj;
    private javax.swing.JPanel T_Lperson;
    private javax.swing.JPanel T_Mobj;
    private javax.swing.JPanel T_Mperson;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel Txt_Calidad;
    private javax.swing.JLabel Txt_Cargo;
    private javax.swing.JLabel Txt_Color;
    private javax.swing.JLabel Txt_Desc;
    private javax.swing.JLabel Txt_Desc1;
    private javax.swing.JLabel Txt_G;
    private javax.swing.JLabel Txt_Gar;
    private javax.swing.JLabel Txt_H;
    private javax.swing.JLabel Txt_Hor;
    private javax.swing.JLabel Txt_Marca;
    private javax.swing.JLabel Txt_Ocup;
    private javax.swing.JLabel Txt_PG;
    private javax.swing.JLabel Txt_Pass;
    private javax.swing.JLabel Txt_R;
    private javax.swing.JLabel Txt_Tamaño;
    private javax.swing.JLabel Txt_Usern;
    private javax.swing.JLabel Txt_Z;
    private javax.swing.JLabel Txt_alt;
    private javax.swing.JLabel Txt_civil;
    private javax.swing.JLabel Txt_com1;
    private javax.swing.JLabel Txt_desc;
    private javax.swing.JLabel Txt_edad;
    private javax.swing.JLabel Txt_id;
    private javax.swing.JLabel Txt_inst;
    private javax.swing.JLabel Txt_nomb;
    private javax.swing.JLabel Txt_pais;
    private javax.swing.JLabel Txt_personadd;
    private javax.swing.JLabel Txt_peso;
    private javax.swing.JLabel Txt_sex;
    private javax.swing.JLabel Txt_sueld;
    private javax.swing.JLabel Txt_ta;
    private javax.swing.JLabel Txt_tall;
    private javax.swing.JLabel Txt_tel;
    private javax.swing.JLabel Txt_tiemp;
    private javax.swing.JLabel Txt_to;
    private javax.swing.JLabel Txt_tp;
    private javax.swing.JButton btn_color;
    private javax.swing.JComboBox<String> cb_TipoC;
    private javax.swing.JComboBox<String> cb_TipoO;
    private javax.swing.JComboBox<String> cb_carg;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.JComboBox<String> cb_tall;
    private javax.swing.JLabel cms;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbs0;
    private javax.swing.JLabel lps;
    private javax.swing.JLabel meses;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JLabel semanas;
    private javax.swing.JScrollPane sp_Desc;
    private javax.swing.JScrollPane sp_Desc1;
    private javax.swing.JTextArea ta_desc;
    private javax.swing.JTextArea ta_descH;
    private javax.swing.JTextArea ta_descS;
    private javax.swing.JTextArea ta_inst;
    private javax.swing.JFormattedTextField tf_AGE;
    private javax.swing.JTextField tf_Calidad;
    private javax.swing.JFormattedTextField tf_ID;
    private javax.swing.JTextField tf_Marca;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JFormattedTextField tf_Tamaño;
    private javax.swing.JTextField tf_Username;
    private javax.swing.JFormattedTextField tf_alt;
    private javax.swing.JFormattedTextField tf_com;
    private javax.swing.JFormattedTextField tf_gar;
    private javax.swing.JTextField tf_hor;
    private javax.swing.JTextField tf_ocup;
    private javax.swing.JTextField tf_pais;
    private javax.swing.JFormattedTextField tf_peso;
    private javax.swing.JFormattedTextField tf_sueld;
    private javax.swing.JFormattedTextField tf_ta1;
    private javax.swing.JTextField tf_tel;
    private javax.swing.JFormattedTextField tf_tiemp;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel unico;
    private javax.swing.JLabel unico2;
    // End of variables declaration//GEN-END:variables
}
